name: Preston Moline
title: Preston Moline
description: My Movie Reviews
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  #- title: Feed
   # url: /feed.xml
email: molinepreston@gmail.com
# See: https://disqus.com/
disqus_username: prestonmoline
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mqkrnjov
